### ISSUE TITLE
Optimizing the block rewards distribution.

### ISSUE THREAD

**Issue by Monster888** [terracoin/proposals#8]
​​This is a very simple proposal. The proposal is to optimize the block rewards distribution.

It's actually 45% miner, 45 masternode, 10% community. It's great but new communities give up to 80% of the block rewards back to the community. 

Terra is a community effort, we should split the rewards to be more efficient. I really think 1/3 should go to miners, 1/3 should go to masternodes and 1/3 should fund our community projects. 

Terra is a balance currency. New competing currencies are coming out giving much more to community projects and I think it's the way to go. 

I think it's time to do this now, and enable Terra to achieve much more in the future.​

**Comment by Eyeswide5hut** [comment]
maybe an issue for when we have more community projects, as it is we need more community projects.

**Comment by Monster888** [comment]
​​Many more community projects will come to Terra, I'm really not concern about that. I'm concern that it's going to be very hard to improve this if we wait too long. 

I own many masternodes and I think we, as Terra community, could accomplish much more to improve the world if we balance this! Are we looking for the best impact we can do to improve this world? 

Also, we will be seen much more as a real community oriented to change the world instead of a community of miners and node owners getting 90% of the rewards. ​

**Comment by lsb108** [comment]
Do something to prove you want TRC to grow. We will always vote to get the reward (salary) .... If you can not do anything ... please do not ask for benefits!

**Comment by Monster888** [comment]
To vote in favor of this proposal. Copy paste this in your wallet:

gobject vote-many ab472fcccec5900673c0748352be320fc6c704d4e01e038d54ad2ad1afacb4ab funding yes


PS: This is a governance vote only and  I'm only asking 10 TRC to refund the proposal submitting fee.

**Comment by hanzac** [comment]
Please also consider the cryptocoins value is based on the security of PoW or PoS. We need the support of miners. Otherwise, the network is under danger of attack.

**Comment by lsb108** [comment]
We need more Dev .... There are many social activities, communication. Otherwise, TRC is just an ordinary altcoin .... nothing special!

**Comment by terracoin** [comment]
You are going to want to put in a revision on this proposal because it has already expired and fallen off the proposals page.  You want the epoch end time to fall right after the next superblock.

As for the proposal itself.  If we reduce the % from 45% to 33% the ROI would be even lower for masternode holders.  Currently it takes about 1100 days for a masternode owner to get their return on investment.  At 33% it would take about 1500 days.  All of the early adopters would be "punished" if this happened.

**Comment by SixOfFive** [comment]
This will create another hardfork as the proposal would require a significant code change. I don't see 10 trc funding a developer to make, test and implement those code changes.

As terracoin pointed out, ROI would drop significantly and those who have already invested in masternodes would be punished. As this stands, its a bad idea and my vote is no.

**Comment by lsb108** [comment]
We hope to have more Dev coming to TRC. We will support, always vote for what DEV do for TRC ... You look at Proposals - Sponsorship - Advertising Football Team ... he has received the consent of everyone . I do not know how well this proposal will grow .... But, look at the points he explains, pay for what, why ..... that's one way to make great suggestions!

**Comment by Monster888** [comment]
Thank you for your comments.

Terra is merge mine with Bitcoin, so security is pretty stable, 33% should be enough for security. 

The MN ROI will be reduce in terms on TRC but will increase in terms of USD because the 33% going to community projects will fund more marketing and projects to bring many more people to our community.

**Comment by SixOfFive** [comment]
Its a snowball effect this would create, 33% (instead of 10%) to community projects, which in turn they immediately sell in order to pay for their proposal costs (say, website hosting, etc .. very few users putting in proposals will end up keeping the terracoin recieved and instead will immediately sell in order to fund their project), which drops the price of terracoin, which in turn reduces the ROI further than just the reduced amount of terracoin recieved by masternode owners, which means masternode owners sell due to low ROI or ROI near zero or negative, which further reduces the value of terracoin. Its a great idea if your trying to kill the value of terracoin and lower the amount of masternode owners (aka investors).

**Comment by Monster888** [comment]
I understand this is early to talk about this since we are just starting to get proposals. I also understand that no masternode owners will vote to reduce the masternode rewards. This is fine.

I agree the ROI is already low. I just think the 10% community will not be enough in the future, to be efficient and also compete with better structured coins. 

Another very good scenario in my opinion would be:
50% masternodes (will increase the MN ROI)
25% mining (should be enough secure since it's merge mine)
25% community (when the proposals will be flowing in, we will grow MUCH faster)

**Comment by lsb108** [comment]
We do not develop TRC under POS. TRC is being exploited by POW ... it is a pity if you want to reduce the% of miners! I think the miners will protest, or they do not exploit!

**Comment by terracoin** [comment]
Just out of curiosity, what coin has an 80% going to the community?  I know of only 2 other coins with dgov at all.

**Comment by Monster888** [comment]
SMARTcash

**Comment by lsb108** [comment]
I have been mining the Smartcash. It has 5 billion coins. With a 1080 GPU, you can get 60 coins a day. Others they are mining with a strong configuration ... they earn 30-50,000 coins a day. The income is more than bitcoin. Therefore, we can not compare!
